# Generated by Django 2.2 on 2021-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biome',
            name='img_src',
        ),
        migrations.AddField(
            model_name='biome',
            name='desc',
            field=models.TextField(default='basic description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biome',
            name='img',
            field=models.ImageField(default='/images/b.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
