# Generated by Django 2.2 on 2021-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0004_auto_20210531_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aniclass',
            name='img_src',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='face_src',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='wide_src',
        ),
        migrations.RemoveField(
            model_name='family',
            name='img_src',
        ),
        migrations.AddField(
            model_name='aniclass',
            name='img',
            field=models.ImageField(default='/images/a.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='face_img',
            field=models.ImageField(default='/images/a.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='wide_img',
            field=models.ImageField(default='/images/a.png', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='img',
            field=models.ImageField(default='/images/a.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
