# Generated by Django 2.2 on 2021-06-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0005_auto_20210531_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aedit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='zoo_app.Animal')),
                ('bedit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='zoo_app.Biome')),
                ('cedit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='zoo_app.Aniclass')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='zoo_app.User')),
                ('fedit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='zoo_app.Family')),
            ],
        ),
    ]
