# Generated by Django 2.2 on 2021-06-01 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0006_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='zoo_app.User'),
        ),
    ]
