# Generated by Django 2.2 on 2021-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0007_auto_20210531_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniclass',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='animal',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='family',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
