# Generated by Django 2.2 on 2021-06-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0008_auto_20210531_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zoo_app.Animal')),
                ('bcomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zoo_app.Biome')),
                ('ccomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zoo_app.Aniclass')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zoo_app.User')),
                ('fcomment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zoo_app.Family')),
            ],
        ),
        migrations.DeleteModel(
            name='Imgtest',
        ),
        migrations.AddField(
            model_name='edit',
            name='text',
            field=models.TextField(default='filler', max_length=50),
            preserve_default=False,
        ),
    ]
